[package]
name = "cons_list"
description = "An implementation of the cons list in Rust"
version = "0.1.0"
edition = "2021"

authors = ["Clement Poh <clement@poh.cc>"]
license = "Apache-2.0"

[dependencies]
